//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainKayit
    {
        public int id { get; set; }
        public string Proje_Adi { get; set; }
        public Nullable<int> Proje_Tip_Id { get; set; }
        public Nullable<int> Yenileme_Periyodu { get; set; }
        public string Domain_Adi { get; set; }
        public Nullable<System.DateTime> Domain_Bitis_Tarihi { get; set; }
        public Nullable<double> Domain_Fiyati { get; set; }
        public string Sunucu { get; set; }
        public Nullable<System.DateTime> Sunucu_Bitis_Tarihi { get; set; }
        public Nullable<double> Sunucu_Fiyati { get; set; }
        public Nullable<bool> SSL { get; set; }
        public Nullable<System.DateTime> SSL_Bitis_Tarihi { get; set; }
        public Nullable<double> SSL_Fiyati { get; set; }
        public string Statik_IP { get; set; }
        public Nullable<System.DateTime> Statik_IP_Bitis_Tarihi { get; set; }
        public Nullable<double> Statik_IP_Fiyati { get; set; }
        public string Metin { get; set; }
    }
}
