//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proje_Tipleri
    {
        public int id { get; set; }
        public string Proje_Tipi { get; set; }
    }
}
